install:
  - cd ../../
  - git clone --branch=development https://github.com/shopgate/${SHOPGATE_THEME}.git ${SHOPGATE_THEME}
  - cd ${SHOPGATE_THEME} && npm i
  - cd ${SHOPGATE_EXTENSIONS}/
  - git clone --branch=development https://github.com/${TRAVIS_REPO_SLUG}.git @${TRAVIS_REPO_SLUG}
  - cd @${TRAVIS_REPO_SLUG}
  - cd frontend/ && npm i
language: node_js
node_js: node
script: "npm run coverage"
# Send coverage report to coveralls.io
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
branches:
  only:
  - development
