language: node_js
node_js: node
before_script: "cd frontend/ && NODE_ENV=development npm i"
script: "cd frontend/ && npm run coverage"
# Send coverage report to coveralls.io
after_script: "cat ./frontend/coverage/lcov.info | ./frontend/node_modules/coveralls/bin/coveralls.js"
branches:
  only:
  - development
