install:
  - cd ../../
  - pwd
  - git clone --branch=development https://github.com/shopgate/${SHOPGATE_THEME}.git ${SHOPGATE_THEME}
  - cd ${SHOPGATE_THEME}
  - pwd
  - cd ${EXTENSIONS}/
  - pwd
  - git clone --branch=development https://github.com/${TRAVIS_REPO_SLUG}.git @${TRAVIS_REPO_SLUG}
  - pwd
  - cd @${TRAVIS_REPO_SLUG}
  - pwd
  #- find ../ -type d | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"
  - cd frontend/
  - ls -al
  - pwd
language: node_js
node_js: node
script: "npm run coverage"
# Send coverage report to coveralls.io
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
branches:
  only:
  - development
