install:
  - git clone https://github.com/$SHOPGATE_THEME_SLUG#development
  - cd $SHOPGATE_THEME_EXTENSIONS
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git @$TRAVIS_REPO_SLUG
language: node_js
node_js: node
before_script: "cd @$TRAVIS_REPO_SLUG/frontend/ && NODE_ENV=development npm i"
script: "npm run coverage"
# Send coverage report to coveralls.io
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
branches:
  only:
  - development
