install:
  # Move to root
  - cd ../../
  # Clone the theme reposirory
  - git clone --branch=${TRAVIS_BRANCH} https://github.com/shopgate/${SHOPGATE_THEME}.git ${SHOPGATE_THEME}
  # Install node modules and switch into extensions folder
  - cd ${SHOPGATE_THEME} && npm i && cd ${SHOPGATE_EXTENSIONS}/
  # Clone the current repository
  - git clone --branch=${TRAVIS_BRANCH} https://github.com/${TRAVIS_REPO_SLUG}.git @${TRAVIS_REPO_SLUG}
  # Move into the folder and install node modules
  - cd @${TRAVIS_REPO_SLUG}/frontend/ && npm i
language: node_js
node_js: node
script: "npm run coverage"
# Send coverage report to coveralls.io
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
branches:
  only:
  - development
